#!/usr/bin/env php
<?php

use App\Commands\ScrapeGitlabCommand;
use App\Commands\ScrapeHitsCommand;
use App\Commands\ScrapeOpenshiftCommand;
use App\Commands\GetDomainDetails;
use Symfony\Component\Console\Application;

set_time_limit(0);
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require __DIR__ . '/vendor/autoload.php';

$application = new Application();
$appVersion = trim(file_get_contents(__DIR__ . '/VERSION'));
$application->setName('Debug CLI');
$application->setVersion($appVersion);
$application->add(new ScrapeOpenshiftCommand());
$application->add(new ScrapeHitsCommand());
$application->add(new ScrapeGitlabCommand());
$application->add(new GetDomainDetails());
$application->run();
